[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "emulite"
version = "0.1.0"
description = "Emulation framework for Android & iOS native libraries"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lief>=0.14",
    "unicorn>=2.1.4",
    "cryptography>=42",
    "capstone>=5",
]

[project.optional-dependencies]
dev = ["mypy>=1.11", "pytest>=8", "ruff>=0.5"]

[project.urls]
Repository = "https://github.com/retrowave3/emulite"
Issues = "https://github.com/retrowave3/emulite/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/emulite"]

[tool.hatch.build.targets.wheel.force-include]
"rootfs/android" = "emulite/rootfs/android"
"src/emulite/py.typed" = "emulite/py.typed"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/rootfs/android",
    "/README.md",
    "/pyproject.toml",
]

[tool.ruff]
line-length = 200

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
files = ["src/emulite/hooks"]
follow_imports = "silent"
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["capstone", "capstone.*"]
ignore_missing_imports = true
