from __future__ import annotations

from typing import Callable, Protocol

import capstone

from emulite.android.android_file_system import AndroidFileSystem
from emulite.android.arm32.android_libc_hooks32 import AndroidLibcHooks32
from emulite.android.arm32.android_syscall_handler32 import AndroidSyscallHandler32
from emulite.android.arm64.android_libc_hooks64 import AndroidLibcHooks64
from emulite.android.arm64.android_syscall_handler64 import AndroidSyscallHandler64
from emulite.android.dalvik_vm import DalvikVM
from emulite.android.java_vm import JavaVM
from emulite.android.jni.jni_env import JNIEnv
from emulite.android.jni.jni_handler import JniHandler
from emulite.android_device import AndroidDevice
from emulite.android_profile import AndroidProfile
from emulite.common.log import Logger
from emulite.cpu.arch.base import Arch
from emulite.cpu.backend import Backend
from emulite.hooks.call_event import CallEvent
from emulite.hooks.disassembler import Disassembler
from emulite.hooks.frame import Frame
from emulite.hooks.hook_handle import HookHandle
from emulite.hooks.hook_manager import HookManager
from emulite.hooks.hook_status import HookStatus
from emulite.hooks.svc_trap import SvcTrap
from emulite.hooks.trace_info import TraceInfo
from emulite.loader.elf_loader import ElfLoader
from emulite.loader.module.native_module import NativeModule
from emulite.loader.module.symbol import Symbol
from emulite.memory import MemoryManager
from emulite.memory.native_pointer import NativePointer


class AndroidEmulatorBase(Protocol):
    rootfs: str
    log: Logger
    profile: AndroidProfile
    device: AndroidDevice
    jni_handler: JniHandler
    arch: Arch
    backend: Backend
    mem: MemoryManager
    auxv: dict[int, int]
    trap: SvcTrap
    loader: ElfLoader
    hooks: HookManager
    disassembler: Disassembler
    vfs: AndroidFileSystem
    jni: JNIEnv
    javavm: JavaVM
    syscalls: AndroidSyscallHandler32 | AndroidSyscallHandler64
    libc: AndroidLibcHooks32 | AndroidLibcHooks64

    def load(self, path_or_name: str, scan_only: bool = False) -> NativeModule: ...
    def call_jni_onload(self, module: NativeModule) -> int: ...
    def find_symbol(self, name: str) -> int | None: ...
    def find_symbol_or_throw(self, name: str) -> int: ...
    def call_symbol(self, name: str, *args: object, **kwargs: object) -> int | NativePointer: ...
    def get_module(self, name_or_path: str) -> NativeModule | None: ...
    def module_at(self, address: int) -> NativeModule | None: ...
    @property
    def modules(self) -> list[NativeModule]: ...
    def add_library_path(self, path: str) -> None: ...
    def describe_address(self, address: int) -> str: ...
    def add_data_symbol(self, name: str, address: int) -> None: ...
    def create_virtual_module(
        self, name: str, symbols: dict[str, int] | None = None
    ) -> NativeModule: ...

    def reg(self, reg_id: int) -> int: ...
    def set_reg(self, reg_id: int, value: int) -> None: ...
    def arg(self, index: int) -> int: ...
    def set_arg(self, index: int, value: int) -> None: ...
    @property
    def sp(self) -> int: ...
    @property
    def pc(self) -> int: ...
    @property
    def lr(self) -> int: ...
    @property
    def ret(self) -> int: ...

    def hook_address(
        self, address: int, callback: Callable[[AndroidEmulatorBase], None]
    ) -> HookHandle: ...
    def hook_symbol(
        self,
        symbol: str,
        on_call: Callable[[AndroidEmulatorBase], HookStatus | None],
        post_call: Callable[[AndroidEmulatorBase], None] | None = None,
        module_name: str | None = None,
    ) -> HookHandle: ...
    def hook_code(
        self,
        callback: Callable[[AndroidEmulatorBase, int, int], None],
        start: int | None = None,
        end: int | None = None,
    ) -> HookHandle: ...
    def hook_module(
        self,
        callback: Callable[[AndroidEmulatorBase, int, int], None],
        module_name: str | None = None,
    ) -> HookHandle: ...
    def trace_code(
        self,
        callback: Callable[[AndroidEmulatorBase, TraceInfo], bool | None],
        start: int | None = None,
        end: int | None = None,
    ) -> HookHandle: ...
    def trace_module(
        self,
        callback: Callable[[AndroidEmulatorBase, TraceInfo], bool | None],
        module_name: str | None = None,
    ) -> HookHandle: ...
    def replace(
        self,
        address: int,
        on_call: Callable[[AndroidEmulatorBase], HookStatus | None],
        post_call: Callable[[AndroidEmulatorBase], None] | None = None,
    ) -> HookHandle: ...
    def hook_memory(
        self,
        callback: Callable[[AndroidEmulatorBase, str, int, int, int], bool | None],
        start: int | None = None,
        end: int | None = None,
        reads: bool = True,
        writes: bool = True,
    ) -> HookHandle: ...
    def watchpoint(
        self,
        address: int,
        callback: Callable[[AndroidEmulatorBase, str, int, int, int], bool | None],
        length: int = 8,
        reads: bool = True,
        writes: bool = True,
    ) -> HookHandle: ...
    def hook_mem_fault(
        self, callback: Callable[[AndroidEmulatorBase, int, int], bool]
    ) -> HookHandle: ...
    def call_trace(
        self,
        callback: Callable[[AndroidEmulatorBase, CallEvent], bool | None],
        module_name: str | None = None,
        *,
        start: int | None = None,
        end: int | None = None,
    ) -> HookHandle: ...
    def disassemble(
        self, address: int, count: int = 1, thumb: bool | None = None
    ) -> list[capstone.CsInsn]: ...
    def backtrace(self, max_depth: int = 64) -> list[Frame]: ...

    def run(self, start: int, until: int, count: int = 0) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> AndroidEmulatorBase: ...
    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None: ...
    def finish(self, return_value: int = 0) -> None: ...
    def call(
        self, target: int | Symbol | NativePointer, *args: object, return_pointer: bool = False
    ) -> int | NativePointer: ...
    def run_pending_irelative(self) -> None: ...
    def run_pending_init(self) -> None: ...

    def ptr(self, address: int) -> NativePointer: ...
    def malloc(self, size: int) -> NativePointer: ...
    def calloc(self, count: int, size: int) -> NativePointer: ...
    def realloc(self, pointer: int | NativePointer, size: int) -> NativePointer: ...
    def free(self, pointer: int | NativePointer) -> None: ...
    def alloc(self, data: bytes | bytearray) -> NativePointer: ...
    def alloc_str(self, text: str) -> NativePointer: ...
    def read_string(self, address: int | NativePointer) -> str: ...

    @property
    def dvm(self) -> DalvikVM: ...
    def get_object(self, ref: int) -> object | None: ...
    def add_file(self, path: str, data: bytes) -> None: ...
    def register_socket(self, path: str, handler: Callable[[bytes], bytes]) -> None: ...
    def register_libc(
        self, name: str, fn: Callable[[AndroidEmulatorBase], object], override: bool = True
    ) -> int: ...
    def java_class(self, name: str) -> object: ...
    def registered_natives(self) -> list: ...
    def call_static_native(
        self, class_name: str, method_name: str, signature: str, *args: object
    ) -> object: ...
    def call_instance_native(
        self, instance: object, class_name: str, method_name: str, signature: str, *args: object
    ) -> object: ...
    def call_native(self, fn: int, this_ref: int, signature: str, args: list) -> object: ...
